name: panvimwiki
channels:
  - conda-forge
  - defaults
dependencies:
  - pandoc[version='>=3.5']
  - panflute[version='<2.1']
  - pip
  - pipx
  - pre-commit
  - pypandoc
  - pytest
  - pytest-cov
  - pytest-freezegun
  - python[version='<3.11']
  - sphinx
  - tox[version='>=4.23.2']
  - pip:
    - -e .
    - vim_bridge3
    - pytest-pretty-terminal
